# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-08 04:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ledger_api_client.ledger_models
#from ledger_api_client.ledger_models import EmailUserRO

class Migration(migrations.Migration):

    dependencies = [
        #migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger_api_client','0002_address_country_document_emailidentity_emailuserro_invoice_privatedocument_useraddress'),
        ('parkstay', '0043_bookinghistory_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canceled_bookings', to="ledger_api_client.EmailUserRO"),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="ledger_api_client.EmailUserRO"),
        ),
    ]
