# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-11 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0062_booking_do_not_send_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='error_sedning_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='error_sending_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
