# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-11 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0063_auto_20200911_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='error_sedning_invoice',
            new_name='error_sending_invoice',
        ),
    ]
