# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0064_auto_20200911_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
