# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-15 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0065_booking_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_group', models.SmallIntegerField(choices=[(0, 'Parkstay Booking Checks')], default=0)),
                ('email', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
