# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0069_auto_20210128_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgroundgroup',
            name='members',
            field=models.ManyToManyField(blank=True, db_table='parkstay_campgroundgroup_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
