# Generated by Django 3.2.4 on 2021-06-17 08:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0003_basket'),
        ('parkstay', '0070_auto_20210514_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('rebuild_gps', models.BooleanField(default=True)),
            ],
        ),
        # Comment out below bookinghistory = invoice when applying this Migrations (once ran uncomment to prevent the migration from being created again)
        # Caused by Model realignment
        # START
        migrations.AddField(
            model_name='bookinghistory',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger_api_client.invoice'),
        ),
        # END 
        migrations.AlterField(
            model_name='booking',
            name='campground',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.campground'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='override_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.discountreason'),
        ),
        migrations.AlterField(
            model_name='campgroundbookingrange',
            name='closure_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.closurereason'),
        ),
        migrations.AlterField(
            model_name='campgroundstayhistory',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkstay.maximumstayreason'),
        ),
        migrations.AlterField(
            model_name='campsitebookingrange',
            name='closure_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.closurereason'),
        ),
        migrations.AlterField(
            model_name='campsiterate',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.pricereason'),
        ),
        migrations.AlterField(
            model_name='campsitestayhistory',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkstay.maximumstayreason'),
        ),
        migrations.AlterField(
            model_name='parkentryrate',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.pricereason'),
        ),
    ]
