# Generated by Django 3.2.4 on 2021-08-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0071_auto_20210617_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='zoom_level',
            field=models.IntegerField(choices=[(0, 'default'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '4'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')], default=-1),
        ),
        migrations.AddField(
            model_name='park',
            name='zoom_level',
            field=models.IntegerField(choices=[(0, 'default'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '4'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')], default=-1),
        ),
        migrations.AddField(
            model_name='places',
            name='zoom_level',
            field=models.IntegerField(choices=[(0, 'default'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '4'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')], default=-1),
        ),
        migrations.AddField(
            model_name='promoarea',
            name='zoom_level',
            field=models.IntegerField(choices=[(0, 'default'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '4'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')], default=-1),
        ),
    ]
