# Generated by Django 3.2.4 on 2021-09-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0074_campsite_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campgroundnotice',
            name='notice_type',
            field=models.IntegerField(choices=[(0, 'Red Warning'), (1, 'Orange Warning'), (2, 'Blue Warning')], default=-1),
        ),
    ]
