# Generated by Django 3.2.4 on 2021-09-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0078_park_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='zoom_level',
            field=models.IntegerField(choices=[(0, 'default'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '4'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')], default=0),
        ),
    ]
