# Generated by Django 3.2.4 on 2021-10-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0079_alter_park_zoom_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
