# Generated by Django 3.2.4 on 2021-10-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0080_booking_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsitebooking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True),
        ),
    ]
