# Generated by Django 3.2.4 on 2021-10-14 03:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0082_peakgroup_peakperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255, unique=True)),
                ('policy_type', models.SmallIntegerField(choices=[(0, 'Per Day'), (1, 'Fixed Fee'), (2, 'Booking Percentage')], default=0)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True)),
                ('grace_time', models.PositiveIntegerField(default=10080)),
                ('peak_policy_enabled', models.BooleanField(default=True)),
                ('peak_policy_type', models.SmallIntegerField(choices=[(0, 'Per Day'), (1, 'Fixed Fee'), (2, 'Booking Percentage')], default=0)),
                ('peak_amount', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True)),
                ('peak_grace_time', models.PositiveIntegerField(default=10080)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('peak_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peak_group_policy', to='parkstay.peakgroup')),
            ],
        ),
    ]
