# Generated by Django 3.2.4 on 2021-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0084_auto_20211015_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampgroundGroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campgroundgroup_id', models.IntegerField()),
                ('emailuser_id', models.IntegerField()),
            ],
            options={
                'db_table': 'parkstay_campgroundgroup_members',
                'managed': False,
            },
        ),
    ]
