# Generated by Django 3.2.4 on 2021-09-17 07:58
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0085_campgroundgroupmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='CampgroundPriceHistory',
            name='booking_policy',
            field=models.IntegerField(blank=True, null=True, unique=True, default=None),
            preserve_default=False,
        ),
    ]

