# Generated by Django 3.2.4 on 2021-10-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0086_campgroundpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsiterate',
            name='booking_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkstay.bookingpolicy'),
        ),
    ]
