# Generated by Django 3.2.4 on 2021-10-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0088_parkstay_campground_pricehistory_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsitebooking',
            name='booking_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_policy', to='parkstay.bookingpolicy'),
        ),
    ]
