# Generated by Django 3.2.4 on 2021-10-26 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0089_campsitebooking_booking_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_description', models.CharField(max_length=150, null=True, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_booking', to='parkstay.booking')),
            ],
        ),
    ]
