# Generated by Django 3.2.4 on 2021-10-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0090_additionalbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkentryrate',
            name='campervan',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='parkentryrate',
            name='trailer',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
