# Generated by Django 3.2.4 on 2021-10-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0093_auto_20211027_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalbooking',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingvehiclerego',
            name='type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('motorbike', 'Motorcycle'), ('concession', 'Vehicle (concession)'), ('campervan', 'Campervan'), ('trailer', 'Trailer')], max_length=10),
        ),
    ]
