# Generated by Django 3.2.4 on 2021-10-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0094_auto_20211028_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsitebooking',
            name='oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
