# Generated by Django 3.2.4 on 2021-10-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0095_campsitebooking_oracle_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campsitebooking',
            old_name='amount',
            new_name='amount_adult',
        ),
        migrations.AddField(
            model_name='campsitebooking',
            name='amount_child',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='campsitebooking',
            name='amount_concession',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='campsitebooking',
            name='amount_infant',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, null=True),
        ),
    ]
