# Generated by Django 3.2.4 on 2021-10-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0096_auto_20211028_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsitebooking',
            name='oracle_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='campsite_oracle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
