# Generated by Django 3.2.4 on 2021-10-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0097_auto_20211028_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpolicy',
            name='no_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='peak_policy_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Fixed Daily'), (1, 'Percentage Daily ')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='policy_type',
            field=models.SmallIntegerField(choices=[(0, 'Fixed Daily'), (1, 'Percentage Daily ')], default=0),
        ),
    ]
