# Generated by Django 3.2.4 on 2021-11-22 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0098_auto_20211029_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='campground_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campground_primary_image', to='parkstay.campgroundimage'),
        ),
    ]
