# Generated by Django 3.2.4 on 2021-11-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0101_auto_20211129_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
