# Generated by Django 3.2.4 on 2021-11-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0102_alter_campsite_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='short_description',
            field=models.TextField(blank=True, max_length=310, null=True),
        ),
    ]
