# Generated by Django 3.2.4 on 2021-11-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0103_alter_campsite_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpolicy',
            name='arrival_limit_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='arrival_time',
            field=models.PositiveIntegerField(blank=True, default=10080, null=True),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='peak_arrival_limit_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpolicy',
            name='peak_arrival_time',
            field=models.PositiveIntegerField(blank=True, default=10080, null=True),
        ),
    ]
