# Generated by Django 3.2.4 on 2021-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0104_auto_20211129_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='motorcycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campsite',
            name='trailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campsite',
            name='vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
