# Generated by Django 3.2.4 on 2021-12-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0105_auto_20211201_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkentryrate',
            name='caravan',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='bookingvehiclerego',
            name='type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('motorbike', 'Motorcycle'), ('concession', 'Vehicle (concession)'), ('campervan', 'Campervan'), ('trailer', 'Trailer'), ('caravan', 'Caravan')], max_length=10),
        ),
    ]
