# Generated by Django 3.2.4 on 2021-12-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0107_alter_bookingvehiclerego_rego'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingvehiclerego',
            unique_together=set(),
        ),
    ]
