# Generated by Django 3.2.4 on 2021-12-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0108_alter_bookingvehiclerego_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingvehiclerego',
            name='hire_car',
            field=models.BooleanField(default=False),
        ),
    ]
