# Generated by Django 3.2.10 on 2021-12-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0109_bookingvehiclerego_hire_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingvehiclerego',
            name='additional_booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
