# Generated by Django 3.2.10 on 2021-12-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0110_bookingvehiclerego_additional_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingvehiclerego',
            name='additional_booking_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
