# Generated by Django 3.2.10 on 2021-12-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0111_alter_bookingvehiclerego_additional_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkstaypermission',
            name='permission_group',
            field=models.SmallIntegerField(choices=[(0, 'Multiple Campsite Selection'), (1, 'Override Price')], default=0),
        ),
    ]
