# Generated by Django 3.2.10 on 2021-12-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0112_alter_parkstaypermission_permission_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campground',
            name='booking_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campground',
            name='campground_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campground',
            name='campsite_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campground',
            name='facilities_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campground',
            name='fee_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campground',
            name='health_and_safety_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campground',
            name='location_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
