# Generated by Django 3.2.10 on 2021-12-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0114_campgroundnotice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgroundnotice',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
