# Generated by Django 3.2.10 on 2021-12-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0115_alter_campgroundnotice_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampsiteBookingLegacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campsite_id', models.IntegerField(blank=True, default=None, null=True)),
                ('date', models.DateField(db_index=True)),
                ('booking_type', models.IntegerField(blank=True, default=None, null=True)),
                ('legacy_booking_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
