# Generated by Django 3.2.10 on 2021-12-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0116_campsitebookinglegacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsitebookinglegacy',
            name='campsite_booking_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
