# Generated by Django 3.2.10 on 2021-12-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0118_auto_20211225_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsitebookinglegacy',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
