# Generated by Django 3.2.12 on 2022-02-10 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0119_campsitebookinglegacy_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampgroundGroupCampgrounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campgroundgroup_id', models.IntegerField()),
                ('campground_id', models.IntegerField()),
            ],
            options={
                'db_table': 'parkstay_campgroundgroup_campgrounds',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='parkstaypermission',
            name='permission_group',
            field=models.SmallIntegerField(choices=[(0, 'Multiple Campsite Selection'), (1, 'Override Price'), (2, 'Cancellation Override (Fees & Refunds)'), (3, 'Cancel a Past Booking'), (4, 'Make Booking Without Payment')], default=0),
        ),
        migrations.CreateModel(
            name='AvailabilityCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stale', models.BooleanField(default=True)),
                ('campground', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availablity_cache', to='parkstay.campground')),
            ],
        ),
    ]
