# Generated by Django 3.2.12 on 2022-03-04 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0120_auto_20220210_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='next_check_for_payment',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='features',
            field=models.ManyToManyField(blank=True, to='parkstay.Feature'),
        ),
    ]
