# Generated by Django 3.2.12 on 2022-03-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0121_auto_20220304_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingvehiclerego',
            name='concession',
            field=models.BooleanField(default=False),
        ),
    ]
