# Generated by Django 3.2.12 on 2022-03-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0122_bookingvehiclerego_concession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='parkstay.Feature'),
        ),
    ]
