# Generated by Django 3.2.12 on 2022-03-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0123_alter_campground_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkstaypermission',
            name='permission_group',
            field=models.SmallIntegerField(choices=[(0, 'Multiple Campsite Selection'), (1, 'Override Price'), (2, 'Cancellation Override (Fees & Refunds)'), (3, 'Cancel a Past Booking'), (4, 'Make Booking Without Payment'), (5, 'Can make advanced booking')], default=0),
        ),
    ]
