# Generated by Django 3.2.12 on 2022-04-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0124_alter_parkstaypermission_permission_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='do_not_send_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
