# Generated by Django 3.2.12 on 2022-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0125_booking_do_not_send_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
