# Generated by Django 3.2.12 on 2022-05-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0126_booking_reminder_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='error_sending_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
