# Generated by Django 3.2.12 on 2022-06-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0127_booking_error_sending_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_managed_booking_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
