# Generated by Django 3.2.12 on 2022-07-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0129_bookinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_hash',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
