# Generated by Django 3.2.12 on 2022-07-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0131_campgroundpermissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampgroundPermissions',
            new_name='CampgroundPermission',
        ),
    ]
