# Generated by Django 3.2.12 on 2022-09-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0132_rename_campgroundpermissions_campgroundpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campgroundpermission',
            name='permission_group',
            field=models.SmallIntegerField(choices=[(0, 'Campground Booking Management')], default=0),
        ),
    ]
