# Generated by Django 3.2.18 on 2023-03-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0133_alter_campgroundpermission_permission_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkentryrate',
            name='gst',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campground',
            name='campground_type',
            field=models.SmallIntegerField(choices=[(0, 'Bookable Online'), (1, 'Not Bookable Online'), (2, 'Other Accomodation'), (3, 'Unpublished'), (4, 'Booking by application')], default=3),
        ),
    ]
