# Generated by Django 3.2.18 on 2023-03-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0134_auto_20230324_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalbooking',
            name='gst',
            field=models.BooleanField(default=True),
        ),
    ]
