# Generated by Django 3.2.18 on 2023-08-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0135_additionalbooking_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBookingNotices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.IntegerField(choices=[(0, 'Red Warning'), (1, 'Orange Warning'), (2, 'Blue Warning'), (3, 'Green Warning')], default=0)),
                ('message', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.IntegerField(choices=[(0, 'Red Warning'), (1, 'Orange Warning'), (2, 'Blue Warning'), (3, 'Green Warning')], default=0)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
    ]
