# Generated by Django 3.2.18 on 2023-08-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0137_auto_20230807_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybookingnotice',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
