# Generated by Django 5.0.8 on 2025-01-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0140_auto_20230818_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='release_time',
            field=models.TimeField(default='10:00:00'),
        ),
    ]
