# Generated by Django 5.0.14 on 2025-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0141_campground_release_time_alter_booking_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampgroundReleaseDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property_cache',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='campsites',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='details',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='vehicles',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='campground',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
