# Generated by Django 5.0.14 on 2025-06-09 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0142_campgroundreleasedate_alter_booking_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campgroundreleasedate',
            name='booking_open_date',
            field=models.DateField(blank=True, help_text='This is the date the booking for until release period', null=True),
        ),
        migrations.AddField(
            model_name='campgroundreleasedate',
            name='campground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campground_release', to='parkstay.campground'),
        ),
        migrations.AlterField(
            model_name='campgroundreleasedate',
            name='release_date',
            field=models.DateField(blank=True, help_text='This means no bookings can be booked from this date.', null=True),
        ),
    ]
