# Generated by Django 5.0.14 on 2025-06-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0143_campgroundreleasedate_booking_open_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campgroundreleasedate',
            unique_together={('release_date', 'booking_open_date', 'campground')},
        ),
    ]
