# Generated by Django 5.0.14 on 2025-06-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0144_alter_campgroundreleasedate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='campgroundreleasedate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
