# Generated by Django 5.0.14 on 2025-06-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0145_campgroundreleasedate_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campgroundreleasedate',
            name='force_rebuild',
            field=models.BooleanField(default=False),
        ),
    ]
