# Generated by Django 5.2.2 on 2025-06-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkstay', '0146_campgroundreleasedate_force_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
